# Generated by Django 2.0 on 2018-01-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
                name='Article',
                fields=[
                    ('id', models.AutoField(auto_created=True,
                                            primary_key=True,
                                            serialize=False,
                                            verbose_name='ID')),
                    ('title', models.CharField(default='title', max_length=32)),
                    ('content', models.TextField(null=True)),
                ],
        ),
    ]
