# Generated by Django 2.0 on 2018-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_public_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public_time',
            field=models.DateTimeField(null=True),
        ),
    ]
